In [3]:
''' 
NumPy(Numerical Python) is a fundamental library for Python numerical computing. It provides efficient multi-dimensional array 
objects and various mathematical functions for handling large datasets making it a critical tool for professionals in fields that 
require heavy computation.
'''
import numpy as np
import time
import sys

In [4]:
arr = np.array([1,2,3,4,5,6])
print(arr,type(arr))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [7]:
#Python List VS numpy Array
'''
Numpy array are faster (optimization in C)
numpy store data in contiguous location   like (1004,1008,1012... )
uses less memory (optimized storage)
built-in mathematical function
supports direct vectorized operations

! why numpy are so fast:
- homogeneous data type and contiguous location
-vector operation and C optimisation
- reduce overhead
'''
size = 1_000_000
py_List = list(range(size))
start = time.time()
sq_list = [x*x for x in py_List]
end = time.time()
print(f"Python list takes time = {end-start:.5f} seconds")
print(f"space occupied by python list = {sys.getsizeof(py_List) * len(py_List)} bytes") 

# numpy
npArr = np.array(py_List)
start = time.time()
npsq_list = npArr**2   # direct method for mathematical calculation make it faster than python_list
end = time.time()
print(f"Python list takes time = {end-start:.5f} seconds")
print(f"space occupied by python list = {npArr.nbytes} bytes")  # np_Array.nbytes -> tells size/memory occupied in bytes 



Python list takes time = 0.11820 seconds
space occupied by python list = 8000056000000 bytes
Python list takes time = 0.00281 seconds
space occupied by python list = 8000000 bytes


In [12]:
# numpy ndArray create from list : way-1
arr = np.array([1,2,3,4,5,6,'python'])  # shape of single dim arr is -> (row,) :(7,) col section is blank
print(arr,arr.dtype,arr.shape)  # npArr.dtype -> used to check the data type of value stored in numpy Array eg: int64, U21 (unicode string)
np_Array = np.array([[1,2,3,4,5],[6,6,7,8,9]])
print(np_Array,type(np_Array),np_Array.shape)  # npArr.shape -> gives us dimension of array like (row,col) :(2,5)

new_Arr = np.array([[1,2,3],[1,2,4],[3,4,6],[6,7,8]])
print(new_Arr,new_Arr.shape)

['1' '2' '3' '4' '5' '6' 'python'] <U21 (7,)
[[1 2 3 4 5]
 [6 6 7 8 9]] <class 'numpy.ndarray'> (2, 5)
[[1 2 3]
 [1 2 4]
 [3 4 6]
 [6 7 8]] (4, 3)


In [21]:
#numpy array creation with help of buildin function
#zeros and ones filled
zeros = np.zeros((3,4),dtype = "int64")
print(zeros,zeros.shape,zeros.dtype)

ones = np.ones((5,) ,dtype = "U21")
print(ones,ones.dtype)

# filled any number use full
mixed = np.full((3,2),100)
print(mixed)

# create a Identity matrix always I = sq matrix
identity = np.eye(3)
print(identity)
# use of arrange method to create a npArray  syntax np.arrange(startVal,exclusiveEndVal,step)
odds = np.arange(1,101,2)  #range element
print(odds,odds.shape)
# linespace kya krta h range = (end - start) -> range/noOfValuePassed  ex 100-1 = 99,ele = 4->99/ele-1 array will be [1,34,67,100]
arr5 = np.linspace(1,100,4)   #evemly spaced array
print(arr5)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4) int64
['1' '1' '1' '1' '1'] <U21
[[100 100]
 [100 100]
 [100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99] (50,)
[  1.  34.  67. 100.]


In [24]:
#proprties
np_Array = np.array([[1,2,3,4],[5,6,7,8]])
print(np_Array.dtype)
print(np_Array.size) # it tell total no of element stored = 8
print(np_Array.ndim) # print the no of dimension -> 2 means 2D array -> n means nD array
#type casting -> converting int type array to float type or any other
float_Array = np_Array.astype(np.float64)
print(float_Array,float_Array.dtype)

int64
8
2
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] float64


In [26]:
#Operations on Arrays
# reshape : means transforming array from dim to another care should be taken size of oldArr and reshaped array always equal
reshapedArr = np_Array.reshape((4,2)) # old dim(2*4) -> new dim (4*2)
print(reshapedArr)
# flatten : means transforming array from n-dim to 1D array
flatten = reshapedArr.flatten()
print(flatten,flatten.shape)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6 7 8] (8,)


In [31]:
# Indexing -> traversal is similar like list or array traversal arr[idx] -> value 
# flatten array = [1 2 3 4 5 6 7 8]
print(flatten[1])
# traverse on n-D array
# float_Array = [[1. 2. 3. 4.]
#              [5. 6. 7. 8.]] 
print(f"1st row, 2nd element is {float_Array[1][2]}")

# fancy indexing
idx = [2,4,7,1]
print(flatten[idx]) # [3 5 8 2]

#Boolean indexing
print(flatten[flatten %2  != 0])
print(flatten[flatten %2  == 0])
print(flatten[flatten <6]) # elements less than idx 6 : [1 2 3 4 5]



2
1st row, 2nd element is 7.0
[3 5 8 2]
[1 3 5 7]
[2 4 6 8]
[1 2 3 4 5]


In [33]:
# slicing very similar to list syntax : np_Array[start:end:step]
print(flatten[2])
print(flatten[2:]) # [3 4 5 6 7 8]
print(flatten[2:5])
print(flatten[2:-1])
print(flatten[::-1]) #[8 7 6 5 4 3 2 1]

3
[3 4 5 6 7 8]
[3 4 5]
[3 4 5 6 7]
[8 7 6 5 4 3 2 1]


In [37]:
# copy vs view
 # python list me copy bnta h sliced part of list ka -> so sliced copy me kiya gya changes ogList me reflect nhi hota but extra memory space aded

 # but in numpy array me view create hota h sliced part ka same array me he so memory efficient but any changes perform on sliced array reflect in ogArray due to view and vice versa
#copy
list = [1,2,3,4,5,6]
slicedList = list[2:-1]  #  # No shared memory with list
print(list,slicedList)
slicedList[0] = -1
print(list,slicedList)  # [1, 2, 3, 4, 5, 6] [-1, 4, 5]

# view
arr = np.array([1,2,3,4,5,6])
slicedArr = arr[2:-1]  # shared memory with arr / shallow copy
print(arr,slicedArr)
slicedArr[0] = -1
print(arr,slicedList)  # [ 1  2 -1  4  5  6] [-1, 4, 5]
#copy method to creat deep copy of npArray
arr1 = np.arange(1,7)
deepCopy = arr1[2:-1].copy() # No shared memory with arr1
deepCopy[0] = -1
print(arr1,deepCopy) # [1 2 3 4 5 6] [-1  4  5]





[1, 2, 3, 4, 5, 6] [3, 4, 5]
[1, 2, 3, 4, 5, 6] [-1, 4, 5]
[1 2 3 4 5 6] [3 4 5]
[ 1  2 -1  4  5  6] [-1, 4, 5]
[1 2 3 4 5 6] [-1  4  5]
